name: Build, test, test all examples

on:
  push:
  pull_request:
    branches: [master, 9.x.x]

env:
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  # build-and-test-ubuntu:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: scripts/ci/build-and-test.sh
  #       env:
  #         NODE_VERSION: ${{ matrix.node-version }}

  build-and-test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
        # node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Fix node-gyp
      #   run: |-
      #     npm install --global node-gyp@latest
      #     npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      #   shell: pwsh
      # - name: Step that prints name of pull request's base branch
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     echo "Pull request's base branch is: ${BASE_BRANCH}"
      #     echo BASE_BRANCH="$BASE_BRANCH" >> $GITHUB_ENV
      #   env:
      #     BASE_BRANCH: ${{ github.base_ref }}
      - run: bash scripts/ci/build-and-test.sh
        shell: bash
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          HEAD_BRANCH: ${{ github.head_ref }}
